# Generated by Django 5.1 on 2024-08-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="Optional: Enter the barcode of the product.",
                max_length=20,
                null=True,
            ),
        ),
    ]
