# Generated by Django 5.1 on 2024-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_foriegn_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="foriegn_product",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select a parent product if this is an alternative.",
                to="products.product",
            ),
        ),
    ]
