# Generated by Django 5.1 on 2024-08-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_foriegn_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="foriegn_product",
            new_name="related_product",
        ),
    ]
