# Generated by Django 5.1 on 2024-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_rename_foriegn_product_product_related_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "Default"),
                    ("PF", "Packaged Food"),
                    ("BEV", "Beverages"),
                    ("CE", "Cooking Essentials"),
                    ("BS", "Baking Supplies"),
                    ("DP", "Dairy Products"),
                    ("MS", "Meat and Seafood"),
                    ("FF", "Frozen Foods"),
                    ("PC", "Personal Care Products"),
                    ("SP", "Sanitary Products"),
                    ("HC", "Household Cleaning Supplies"),
                    ("HW", "Health and Wellness"),
                    ("BP", "Baby Products"),
                    ("PS", "Pet Supplies"),
                    ("IF", "International and Specialty Foods"),
                ],
                default="DEFAULT",
                help_text="Select the category of the product.",
                max_length=10,
            ),
        ),
    ]
